kill-chat-enabled: true
kill-chat-messages:
  - "gg"
  - "loser"
  - "LOL"
  - "Get rekt!"
  - "Too easy!"
  - "Nice try!"
  - "Owned!"
  - "TheWindows is goat!"
  - "HAHAHAHA"
  - "Blud died to a bot"
  - "shush"
max-fake-players: 10
default-behaviors:
  spectron:auto_equip_armor: []
  spectron:auto_equip_sword: []
  spectron:pvp:
    reach_distance: 4
    pvp_idle_time: 500
auto-spawn-on-start: true
configured-players-add-delay: 20
pvp-enabled: true
random-walk-enabled: true
pvp-reach-distance: 4
pvp-damage-cooldown: 10
pvp-difficulty: normal